# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'To_Do.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(814, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_itemNum = QtWidgets.QLabel(self.centralwidget)
        self.label_itemNum.setGeometry(QtCore.QRect(450, 90, 201, 41))
        self.label_itemNum.setObjectName("label_itemNum")
        self.button_Add = QtWidgets.QPushButton(self.centralwidget)
        self.button_Add.setGeometry(QtCore.QRect(450, 320, 151, 51))
        self.button_Add.setObjectName("button_Add")
        self.button_Del = QtWidgets.QPushButton(self.centralwidget)
        self.button_Del.setGeometry(QtCore.QRect(640, 320, 161, 51))
        self.button_Del.setObjectName("button_Del")
        self.textEdit_Descripton = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Descripton.setGeometry(QtCore.QRect(450, 200, 341, 91))
        self.textEdit_Descripton.setObjectName("textEdit_Descripton")
        self.label_Description = QtWidgets.QLabel(self.centralwidget)
        self.label_Description.setGeometry(QtCore.QRect(450, 150, 261, 41))
        self.label_Description.setObjectName("label_Description")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(130, 470, 201, 61))
        self.button_clear.setObjectName("button_clear")
        self.label_ThingsToDo = QtWidgets.QLabel(self.centralwidget)
        self.label_ThingsToDo.setGeometry(QtCore.QRect(40, 40, 341, 41))
        self.label_ThingsToDo.setObjectName("label_ThingsToDo")
        self.spinBox_itemNum = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_itemNum.setGeometry(QtCore.QRect(661, 91, 121, 41))
        self.spinBox_itemNum.setMaximum(999)
        self.spinBox_itemNum.setObjectName("spinBox_itemNum")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 80, 381, 371))
        self.listWidget.setObjectName("listWidget")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(450, 390, 331, 150))
        self.label_error.setObjectName("label_error")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 22))
        self.menubar.setObjectName("menubar")
        self.menuTO_DO_List = QtWidgets.QMenu(self.menubar)
        self.menuTO_DO_List.setObjectName("menuTO_DO_List")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTO_DO_List.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_itemNum.setText(_translate("MainWindow", "Item Number:"))
        self.button_Add.setText(_translate("MainWindow", "Add Item"))
        self.button_Del.setText(_translate("MainWindow", "Delete Item"))
        self.label_Description.setText(_translate("MainWindow", "Item Description:"))
        self.button_clear.setText(_translate("MainWindow", "Clear List"))
        self.label_ThingsToDo.setText(_translate("MainWindow", "Things to do:"))
        self.label_error.setText(_translate("MainWindow",
                                            "Note:\"Add Item\"\\\"Delete\nItem\" adds\\deletes the item\nat the end of the list when\n\"Item Number\" is set to 0."))
        self.menuTO_DO_List.setTitle(_translate("MainWindow", "To-Do List"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
